language: r
sudo: false
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - ./travis-tool.sh install_github jimhester/covr
  - Rscript -e 'library(covr);codecov()'